version: "3.7"
services:
  vpn:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 1101:1194/udp
      - 8001:8000
    environment:
      - WEB_SECRET_TOKEN=example_web_secret
    cap_add:
      - NET_ADMIN
    volumes:
      - vpn_data:/etc/openvpn
    networks:
      my_net:
        ipv4_address: 10.10.1.2
volumes:
  vpn_data:
    name: vpn_data
networks:
  my_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.1.0/24
          gateway: 10.10.1.1
