version: '3.3'
services:
	ovpn:
		ports:
			- 1194:1194/udp
			- 8080:8000
		environment:
			- WEB_SECRET_TOKEN=example_web_secret
			- OVPN_ROUTES=
		cap_add:
			- NET_ADMIN
		build:
			dockerfile: Dockerfile
		volumes:
			- data:/etc/openvpn
		networks:
			ad_net:
				ipv4_address: 10.10.0.254
volumes:
	data:
networks:
	ad_net:
		driver: bridge
		ipam:
			driver: default
			config:
				- subnet: 10.10.0.0/16
				  gateway: 10.10.0.1
